namespace Files_Extensions
{
	enum UserInteractionType
	{
		MouseInDesktopMode = 0,
		TouchInDesktopMode = 1,
		MouseInTabletMode = 2,
		TouchInTabletMode = 3
	};

	[default_interface]
	runtimeclass UserInteractionMode
	{
		UserInteractionMode();
		event Windows.Foundation.EventHandler<UserInteractionType> UserInteractionModeChanged;
		UserInteractionType GetUserInteractionMode();
		Int32 GetSlateState();
		Int32 GetDockState();
	}
}