version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      windows-app-sdk:
        patterns:
          - "Microsoft.WindowsAppSDK"
          - "Microsoft.WindowsAppSDK.*"
          - "Microsoft.Windows.AI.MachineLearning"
