commit_message: 'fix: new translations in %original_file_name% (%original_file_name%) from Crowdin'
append_commit_message: 
files:
  - source: /src/Files.App/Strings/en-US/*.resw
    translation: /src/Files.App/Strings/%locale%/%original_file_name%
