name: Bug Report
description: Create a bug report to help improve Files
labels: [bug]
body:

  # Description
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  # Step To Reproduce
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  # Requirements
  - type: textarea
    attributes:
      label: Requirements
      description: describe the expected behavior (eg. Fix crash that occurs when...). If left blank, the issue will likely be closed without discussion.
      placeholder: |
        - e.g. Fix crash that occurs when...
    validations:
      required: true

  # Files Version
  - type: input
    id: files_version
    attributes:
      label: Files Version
      description: Which version of Files are you using? The version number can be found by going to Files' Settings > About
      placeholder: "e.g. Version: 2.0.34.0"
    validations:
      required: true

  # Windows Version
  - type: dropdown
    id: windows_version
    attributes:
      label: Windows Version
      description: Which version of Windows are you using?
      multiple: true
      options:
        - Windows 10
        - Windows 10 Release Preview
        - Windows 10 Beta
        - Windows 10 Dev
        - Windows 10 Canary
        - Windows 11
        - Windows 11 Release Preview
        - Windows 11 Beta
        - Windows 11 Dev
        - Windows 11 Canary
    validations:
      required: true

  # Log File
  - type: textarea
    attributes:
      label: Log File
      description: |
        Please upload the log file as an attachment (DO NOT COPY OR PASTE THE CONTENTS INTO THIS FIELD)
      placeholder: |
        To upload the log, access it from Settings -> About -> Open log location; Or
        - Select the `debug.log` file from `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`
        - Drag and drop the file to upload as an attachment 
    validations:
      required: true
