name: Bug Report
description: Create a bug report to help improve Files
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: files-version
    attributes:
      label: Files Version
      description: What version of Files are you using?
      placeholder: v1.5
    validations:
      required: true
  - type: input
    attributes:
      label: Windows Version
      description: What version of Windows are you using? Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> and copy.
      placeholder: e.g. Windows 10 20H2 19042.804
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Assets
      description: |
        A list of assets (logs, screenshots) relevant to this bug.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: |
        To upload the log, access it from Settings -> About -> Open log location; Or
        - Copy the `debug.log` and `debug_fulltrust.log` files from `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`
        - Drag and drop them into this text area.
