name: Bug Report
description: Create a bug report to help improve Files
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '....'
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Requirements
      description: describe all the requirements to fix the issue (eg. Fix crash that occurs when...). If left blank, the issue will likely be closed without discussion.
      value: |
        - eg. Fix crash that occurs when...
        - eg. Correct action happens when clicking...
    validations:
      required: true
  - type: input
    id: files-version
    attributes:
      label: Files Version
      description: Which version of Files are you using? The version number can be found by going to Files' Settings > About
      placeholder: "e.g. Version: 2.0.34.0 OS Version: 10.0.22000.000"
    validations:
      required: true
  - type: input
    attributes:
      label: Windows Version
      description: Which version of Windows are you using? Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> and copy.
      placeholder: e.g. Windows 11 21H2 22000.000
    validations:
      required: true
  - type: textarea
    attributes:
      label: Log file
      description: |
        This issue will be closed if the apps log file is not attatched.
      placeholder: |
        To upload the log, access it from Settings -> About -> Open log location; Or
        - Select the `debug.log` file from `%localappdata%\Packages\49306atecsolution.FilesUWP_et10x9a9vyk8t\LocalState`
        - Upload the file as an attachment
    validations:
      required: true
