blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://discord.gg/files
    about: Suggest an idea for Files.
  - name: Translation issue
    url: https://crowdin.com/project/files-app
    about: Help improve translations on Crowdin.
  - name: Question & Discussion
    url: https://discord.gg/files
    about: Post your questions and join the discussion. You can participate in chats on every channel.
  - name: Code Quality
    url: https://discord.gg/files
    about: Discuss code quality and improvements on our Discord server.
