name: Feature Request
description: This project thrives from differentiation from competing apps. Suggest an idea for Files.
type: 'Feature request'
title: 'Feature: '
body:

  # Tip to warn of checking for existing issues
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        >Have you checked for similar feature requests? There's a possibility your suggestion is already being tracked. Please do a thorough search before creating a new issue.

  # Description
  - type: textarea
    attributes:
      label: What feature or improvement do you think would benefit Files?
      description: Please include your use case
    validations:
      required: true

  # Tooltip about Requirements
  - type: markdown
    attributes:
      value: |
        ---

        What will need to change in order for this feature to be implemented? A good rule of thumb is to start your proposal with no more than 7 high-level requirements.

  # Requirements
  - type: textarea
    attributes:
      label: Requirements
      description: Describe all the requirements to make your idea happen.
      value: |
        - This proposal will accomplish X
        - This proposal will accomplish Y
        - This proposal will accomplish Z
    validations:
      required: true

  # Files Version
  - type: input
    id: files_version
    attributes:
      label: Files Version
      description: Which version of Files are you using? To copy your Files version, access it from Settings -> About -> Copy -> Files version.
      placeholder: 'e.g. 2.0.36.0'
    validations:
      required: true

  # Additional Comments
  - type: textarea
    attributes:
      label: Comments
      description: Additional information, comments or screenshots about the feature request.
