name: Feature Request
description: This project thrives from differentiation from competing apps. Suggest an idea for Files
labels: [feature request]
body:
  - type: textarea
    attributes:
      label: What feature or improvement do you think would benefit Files?
      description: Please include your use case
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---

        Please include a list changes required to make this improvement. A good rule of thumb is to start your proposal with no more than 7 high-level requirements.
  - type: textarea
    attributes:
      label: Requirements
      description: Describe all the requirements to make your idea happen
      value: |
        - This proposal will accomplish X
        - This proposal will accomplish Y
        - This proposal will accomplish Z
    validations:
      required: true
  - type: input
    id: files-version
    attributes:
      label: Files Version
      description: Which version of Files are you currently using?
      placeholder: 'Version: 2.0.36.0'
    validations:
      required: true
  - type: input
    attributes:
      label: Windows Version
      description: Which version of Windows are you currently using? Press <kbd>Win</kbd> + <kbd>Pause/Break</kbd> and copy.
      placeholder: e.g. Windows 11 21H2 22000.194
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comments
      description: Additional information, comments or screenshots about the feature request.
