name: Feature Request
description: This project thrives from differentiation from competing apps. Suggest an idea for Files
labels: [feature request]
body:

  # Description
  - type: textarea
    attributes:
      label: What feature or improvement do you think would benefit Files?
      description: Please include your use case
    validations:
      required: true

  # Tooltip about Requirements
  - type: markdown
    attributes:
      value: |
        ---

        Please include a list changes required to make this improvement. A good rule of thumb is to start your proposal with no more than 7 high-level requirements.

  # Requirements
  - type: textarea
    attributes:
      label: Requirements
      description: Describe all the requirements to make your idea happen
      value: |
        - This proposal will accomplish X
        - This proposal will accomplish Y
        - This proposal will accomplish Z
    validations:
      required: true

  # Files Version
  - type: input
    id: files-version
    attributes:
      label: Files Version
      description: Which version of Files are you currently using?
      placeholder: 'Version: 2.0.36.0'
    validations:
      required: true

  # Windows Version
  - type: dropdown
    id: windows_version
    attributes:
      label: Windows Version
      description: Which version of Windows are you using?
      multiple: true
      options:
        - 'Windows 11 Insider: 25xxx series'
        - 'Windows 11 Insider: 23xxx series'
        - 'Windows 11 (22H2): 22621'
        - 'Windows 11 (21H2): 22000'
        - 'Windows 10 (22H2): 19045'
        - 'Windows 10 (21H2): 19044'
        - 'Windows 10 (21H1): 19043'
        - 'Windows 10 (20H2): 19042'
        - 'Windows 10 (2004): 19041'
    validations:
      required: true

  # Additional Comments
  - type: textarea
    attributes:
      label: Comments
      description: Additional information, comments or screenshots about the feature request.
