// Copyright (c) Files Community
// Licensed under the MIT License.

using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Files.Core.SourceGenerator.Generators;

[Generator]
internal sealed class GeneratedSettingsPropertyGenerator : IIncrementalGenerator
{
	private const string AttributeMetadataName = "Files.Shared.Attributes.GeneratedSettingsPropertyAttribute";

	private static readonly SymbolDisplayFormat FullyQualifiedWithNullable = SymbolDisplayFormat.FullyQualifiedFormat
		.WithMiscellaneousOptions(SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
			AttributeMetadataName,
			static (node, _) => node is PropertyDeclarationSyntax,
			static (ctx, _) => (IPropertySymbol)ctx.TargetSymbol);

		var collected = provider.Collect();
		context.RegisterSourceOutput(collected, Execute);
	}

	private static void Execute(SourceProductionContext context, ImmutableArray<IPropertySymbol> properties)
	{
		if (properties.IsDefaultOrEmpty)
			return;

		foreach (var group in properties.GroupBy(static p => p.ContainingType, SymbolEqualityComparer.Default))
		{
			if (group.Key is not INamedTypeSymbol typeSymbol)
				continue;

			var diagnostics = new List<Diagnostic>();
			var code = EmitType(typeSymbol, group, diagnostics);
			foreach (var diagnostic in diagnostics)
				context.ReportDiagnostic(diagnostic);

			if (code is not null)
				context.AddSource($"{typeSymbol.Name}.GeneratedSettingsProperties.g.cs", code);
		}
	}

	private static string? EmitType(INamedTypeSymbol typeSymbol, IEnumerable<IPropertySymbol> props, List<Diagnostic> diagnostics)
	{
		var properties = props
			.OfType<IPropertySymbol>()
			.GroupBy(static p => p.Name, StringComparer.Ordinal)
			.Select(static g => g.First())
			.OrderBy(static p => p.Name)
			.ToArray();
		if (properties.Length == 0)
			return null;

		var ns = typeSymbol.ContainingNamespace?.IsGlobalNamespace is false
			? typeSymbol.ContainingNamespace.ToDisplayString()
			: null;

		var sb = new StringBuilder();
		_ = sb.AppendLine("// <auto-generated/>");
		_ = sb.AppendLine("#nullable enable");
		_ = sb.AppendLine("using System.Buffers;");
		_ = sb.AppendLine("using System;");
		_ = sb.AppendLine("using System.Text;");
		_ = sb.AppendLine("using System.Text.Json;");
		_ = sb.AppendLine("using System.Text.Json.Serialization;");
		_ = sb.AppendLine();

		if (ns is not null)
		{
			_ = sb.AppendLine($"namespace {ns};");
			_ = sb.AppendLine();
		}

		_ = sb.AppendLine($"partial class {typeSymbol.Name}");
		_ = sb.AppendLine("{");

		_ = sb.AppendLine("\tprotected override string SerializeCore()");
		_ = sb.AppendLine("\t{");
		_ = sb.AppendLine("\t\tvar buffer = new ArrayBufferWriter<byte>();");
		_ = sb.AppendLine("\t\tusing var writer = new Utf8JsonWriter(buffer, new JsonWriterOptions { Indented = true });");
		_ = sb.AppendLine($"\t\tJsonSerializer.Serialize(writer, this, SettingsJsonContext.Default.{typeSymbol.Name});");
		_ = sb.AppendLine("\t\twriter.Flush();");
		_ = sb.AppendLine("\t\treturn Encoding.UTF8.GetString(buffer.WrittenSpan);");
		_ = sb.AppendLine("\t}");
		_ = sb.AppendLine();
		_ = sb.AppendLine("\tprotected override void DeserializeCore(string json)");
		_ = sb.AppendLine("\t{");
		_ = sb.AppendLine($"\t\tvar loaded = JsonSerializer.Deserialize(json, SettingsJsonContext.Default.{typeSymbol.Name}) as {typeSymbol.Name};");
		_ = sb.AppendLine("\t\tif (loaded is null)");
		_ = sb.AppendLine("\t\t\treturn;");
		_ = sb.AppendLine();
		_ = sb.AppendLine("\t\tusing (BeginHydrationScope())");
		_ = sb.AppendLine("\t\t{");
		foreach (var p in properties)
		{
			_ = sb.AppendLine($"\t\t\t__{p.Name} = loaded.__{p.Name};");
		}
		_ = sb.AppendLine("\t\t}");
		_ = sb.AppendLine("\t}");
		_ = sb.AppendLine();

		foreach (var p in properties)
		{
			var defaultExpr = TryGetDefaultCallbackExpression(p) ?? TryGetDefaultExpression(p, diagnostics);
			if (defaultExpr is null)
				defaultExpr = GetTypeDefaultExpression(p.Type);

			var getValueCallback = TryGetStringNamedArgument(p, "GetValueCallback");
			var typeName = p.Type.ToDisplayString(FullyQualifiedWithNullable);
			_ = sb.AppendLine("\t[JsonIgnore]");
			_ = sb.AppendLine($"\tprivate {typeName} __{p.Name} = {defaultExpr};");
			_ = sb.AppendLine();
			_ = sb.AppendLine($"\tpublic partial {typeName} {p.Name}");
			_ = sb.AppendLine("\t{");
			_ = sb.AppendLine(getValueCallback is null
				? $"\t\tget => __{p.Name};"
				: $"\t\tget => {getValueCallback}(__{p.Name});");
			_ = sb.AppendLine($"\t\tset => SetProperty(ref __{p.Name}, value);");
			_ = sb.AppendLine("\t}");
			_ = sb.AppendLine();
		}

		_ = sb.AppendLine("}");
		return sb.ToString();
	}

	private static string? TryGetDefaultCallbackExpression(IPropertySymbol property)
	{
		var callback = TryGetStringNamedArgument(property, "DefaultValueCallback");
		return callback is null
			? null
			: $"{callback}()";
	}

	private static string? TryGetStringNamedArgument(IPropertySymbol property, string name)
	{
		var attr = property.GetAttributes().FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == AttributeMetadataName);
		if (attr is null)
			return null;

		var named = attr.NamedArguments.FirstOrDefault(kv => kv.Key == name);
		if (named.Equals(default(KeyValuePair<string, TypedConstant>)))
			return null;

		return named.Value.Value as string;
	}

	private static string? TryGetDefaultExpression(IPropertySymbol property, List<Diagnostic> diagnostics)
	{
		var attr = property.GetAttributes().FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == AttributeMetadataName);
		if (attr is null)
			return null;

		var named = attr.NamedArguments.FirstOrDefault(static kv => kv.Key == "DefaultValue");
		if (named.Equals(default(KeyValuePair<string, TypedConstant>)))
			return null;

		var constant = named.Value;
		var expr = FormatDefault(constant, property.Type);
		if (expr is null)
		{
			diagnostics.Add(Diagnostic.Create(
				new DiagnosticDescriptor(
					"FSG2001",
					"Unsupported default value",
					"DefaultValue for property '{0}' has an unsupported type",
					"Design",
					DiagnosticSeverity.Error,
					isEnabledByDefault: true),
				property.Locations.FirstOrDefault(),
				property.Name));
		}

		return expr;
	}

	private static string GetTypeDefaultExpression(ITypeSymbol type)
	{
		if (type.NullableAnnotation == NullableAnnotation.Annotated || type.IsReferenceType)
			return "default!";

		var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		return $"default({typeName})";
	}

	private static string? FormatDefault(TypedConstant constant, ITypeSymbol targetType)
	{
		if (constant.IsNull)
			return targetType.IsReferenceType || targetType.NullableAnnotation == NullableAnnotation.Annotated
				? "null"
				: GetTypeDefaultExpression(targetType);

		if (targetType.TypeKind == TypeKind.Enum)
		{
			var enumType = targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			return $"({enumType}){FormatNumericLiteral(constant.Value)}";
		}

		return constant.Value switch
		{
			string s => $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"",
			bool b => b ? "true" : "false",
			char c => $"'{(c == '\'' ? "\\'" : c.ToString())}'",
			byte or sbyte or short or ushort or int => Convert.ToString(constant.Value, System.Globalization.CultureInfo.InvariantCulture),
			uint u => $"{u}U",
			long l => $"{l}L",
			ulong ul => $"{ul}UL",
			float f => $"{f.ToString(System.Globalization.CultureInfo.InvariantCulture)}F",
			double d => $"{d.ToString(System.Globalization.CultureInfo.InvariantCulture)}D",
			decimal m => $"{m.ToString(System.Globalization.CultureInfo.InvariantCulture)}M",
			_ => null,
		};
	}

	private static string FormatNumericLiteral(object? value)
	{
		return value switch
		{
			byte or sbyte or short or ushort or int => Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture)!,
			uint u => $"{u}U",
			long l => $"{l}L",
			ulong ul => $"{ul}UL",
			_ => "0",
		};
	}
}
