// Copyright (c) Files Community
// Licensed under the MIT License.

using Windows.Foundation;

namespace Files.App.Controls;

/// <summary>
/// A panel that arranges content children and positions <see cref="ResizeVisual"/> children
/// overlapping the dividing lines between adjacent items, enabling interactive resizing.
/// </summary>
/// <remarks>
/// Set <see cref="Orientation"/> to <see cref="Orientation.Horizontal"/> (default) for
/// left-to-right layout or <see cref="Orientation.Vertical"/> for top-to-bottom layout.
/// When no explicit <see cref="ResizeVisual"/> children are present, the panel automatically
/// generates one for every content child except the last, enabling interactive resizing out of
/// the box.
/// </remarks>
public partial class ResizablePanel : Panel
{
    private bool _autoGeneratedResizeVisuals;

    protected override Size MeasureOverride(Size availableSize)
    {
        EnsureResizeVisuals();

        bool isHorizontal = Orientation is Orientation.Horizontal;
        double totalPrimary = 0;
        double maxSecondary = 0;

        foreach (var child in Children)
        {
            child.Measure(isHorizontal
                ? new Size(double.PositiveInfinity, availableSize.Height)
                : new Size(availableSize.Width, double.PositiveInfinity));

            if (child is not ResizeVisual)
            {
                if (isHorizontal)
                {
                    totalPrimary += child.DesiredSize.Width;
                    maxSecondary = Math.Max(maxSecondary, child.DesiredSize.Height);
                }
                else
                {
                    totalPrimary += child.DesiredSize.Height;
                    maxSecondary = Math.Max(maxSecondary, child.DesiredSize.Width);
                }
            }
        }

        return isHorizontal
            ? new Size(totalPrimary, maxSecondary)
            : new Size(maxSecondary, totalPrimary);
    }

    protected override Size ArrangeOverride(Size finalSize)
    {
        bool isHorizontal = Orientation is Orientation.Horizontal;

        // First pass: arrange content children sequentially and record their positions
        var contentPositions = new Dictionary<UIElement, double>();
        double offset = 0;

        foreach (var child in Children)
        {
            if (child is ResizeVisual)
                continue;

            if (isHorizontal)
            {
                var width = child.DesiredSize.Width;
                child.Arrange(new Rect(offset, 0, width, finalSize.Height));
                contentPositions[child] = offset;
                offset += width;
            }
            else
            {
                var height = child.DesiredSize.Height;
                child.Arrange(new Rect(0, offset, finalSize.Width, height));
                contentPositions[child] = offset;
                offset += height;
            }
        }

        // Second pass: arrange resize visuals at the same origin as their targets.
        // The ResizeVisual's internal TranslateTransform centers it on the target's trailing edge.
        foreach (var child in Children)
        {
            if (child is ResizeVisual rv &&
                rv.Target is { } target &&
                contentPositions.TryGetValue(target, out var targetOffset))
            {
                if (isHorizontal)
                    rv.Arrange(new Rect(targetOffset, 0, rv.DesiredSize.Width, finalSize.Height));
                else
                    rv.Arrange(new Rect(0, targetOffset, finalSize.Width, rv.DesiredSize.Height));
            }
        }

        return isHorizontal
            ? new Size(offset, finalSize.Height)
            : new Size(finalSize.Width, offset);
    }

	/// <summary>
	/// Ensures auto-generated <see cref="ResizeVisual"/> children are present and valid.
	/// On every measure pass this validates that existing visuals still match the current
	/// content children in count and target order, regenerating them when they become stale
	/// (e.g. after an <see cref="ItemsControl"/> reorders its containers).
	/// </summary>
	private void EnsureResizeVisuals()
	{
		// Single pass: collect content children and existing resize visuals
		var contentChildren = new List<UIElement>();
		var existingResizeVisuals = new List<ResizeVisual>();

		foreach (var child in Children)
		{
			if (child is ResizeVisual rv)
				existingResizeVisuals.Add(rv);
			else
				contentChildren.Add(child);
		}

		int expectedCount = Math.Max(0, contentChildren.Count - 1);

		if (_autoGeneratedResizeVisuals)
		{
			// Validate: correct count and every target matches the current content order
			if (existingResizeVisuals.Count == expectedCount)
			{
				bool valid = true;
				for (int i = 0; i < expectedCount; i++)
				{
					if (existingResizeVisuals[i].Target != contentChildren[i])
					{
						valid = false;
						break;
					}
				}

				if (valid)
					return;
			}

			// Stale or missing — remove before regenerating
			for (int i = existingResizeVisuals.Count - 1; i >= 0; i--)
				Children.Remove(existingResizeVisuals[i]);

			existingResizeVisuals.Clear();
			_autoGeneratedResizeVisuals = false;
		}

		// If user-provided resize visuals exist, skip auto-generation
		if (existingResizeVisuals.Count > 0)
			return;

		if (contentChildren.Count < 2)
			return;

		_autoGeneratedResizeVisuals = true;

		bool isHorizontal = Orientation is Orientation.Horizontal;

		for (int i = 0; i < expectedCount; i++)
		{
			var rv = new ResizeVisual
			{
				Orientation = isHorizontal ? Orientation.Horizontal : Orientation.Vertical,
				Target = contentChildren[i] as FrameworkElement,
			};

			if (isHorizontal)
				rv.Width = 32;
			else
				rv.Height = 32;

			Children.Add(rv);
		}
	}

	/// <summary>
	/// Forces regeneration of auto-generated <see cref="ResizeVisual"/> children on the next
	/// measure pass. Call this when the panel's content children have been externally modified
	/// (e.g., reordered, added, or removed).
	/// </summary>
	public void InvalidateAutoGeneration()
	{
		_autoGeneratedResizeVisuals = false;

		for (int i = Children.Count - 1; i >= 0; i--)
		{
			if (Children[i] is ResizeVisual)
				Children.RemoveAt(i);
		}

		InvalidateMeasure();
	}
}
