// Copyright (c) Files Community
// SPDX-License-Identifier: MPL-2.0

using System.Text.Json.Serialization.Metadata;

namespace Files.App.Utils.Serialization
{
	/// <summary>
	/// Source-generated serialization metadata for value types (enums, nullable primitives).
	/// Native AOT cannot instantiate System.Text.Json's generic converters over value types
	/// at runtime, so every enum that can appear in serialized data must be listed here.
	/// Reference types are handled by the reflection resolver fallback in <see cref="AotJson.Options"/>.
	/// </summary>
	[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
	[JsonSerializable(typeof(AccessControlEntryType))]
	[JsonSerializable(typeof(AccessControlEntryType?))]
	[JsonSerializable(typeof(AccessControlEntryFlags))]
	[JsonSerializable(typeof(AccessControlEntryFlags?))]
	[JsonSerializable(typeof(AccessControlPrincipalType))]
	[JsonSerializable(typeof(AccessControlPrincipalType?))]
	[JsonSerializable(typeof(AccessMaskFlags))]
	[JsonSerializable(typeof(AccessMaskFlags?))]
	[JsonSerializable(typeof(ActionCategory))]
	[JsonSerializable(typeof(ActionCategory?))]
	[JsonSerializable(typeof(AddItemDialogItemType))]
	[JsonSerializable(typeof(AddItemDialogItemType?))]
	[JsonSerializable(typeof(AppEnvironment))]
	[JsonSerializable(typeof(AppEnvironment?))]
	[JsonSerializable(typeof(ArchiveCompressionLevels))]
	[JsonSerializable(typeof(ArchiveCompressionLevels?))]
	[JsonSerializable(typeof(ArchiveDictionarySizes))]
	[JsonSerializable(typeof(ArchiveDictionarySizes?))]
	[JsonSerializable(typeof(ArchiveFormats))]
	[JsonSerializable(typeof(ArchiveFormats?))]
	[JsonSerializable(typeof(ArchiveSplittingSizes))]
	[JsonSerializable(typeof(ArchiveSplittingSizes?))]
	[JsonSerializable(typeof(ArchiveWordSizes))]
	[JsonSerializable(typeof(ArchiveWordSizes?))]
	[JsonSerializable(typeof(BackdropMaterialType))]
	[JsonSerializable(typeof(BackdropMaterialType?))]
	[JsonSerializable(typeof(CardsViewSizeKind))]
	[JsonSerializable(typeof(CardsViewSizeKind?))]
	[JsonSerializable(typeof(ColumnsViewSizeKind))]
	[JsonSerializable(typeof(ColumnsViewSizeKind?))]
	[JsonSerializable(typeof(ContextMenuFlyoutItemType))]
	[JsonSerializable(typeof(ContextMenuFlyoutItemType?))]
	[JsonSerializable(typeof(DateTimeFormats))]
	[JsonSerializable(typeof(DateTimeFormats?))]
	[JsonSerializable(typeof(DeleteConfirmationPolicies))]
	[JsonSerializable(typeof(DeleteConfirmationPolicies?))]
	[JsonSerializable(typeof(DetailsViewSizeKind))]
	[JsonSerializable(typeof(DetailsViewSizeKind?))]
	[JsonSerializable(typeof(DialogResult))]
	[JsonSerializable(typeof(DialogResult?))]
	[JsonSerializable(typeof(DynamicDialogButtons))]
	[JsonSerializable(typeof(DynamicDialogButtons?))]
	[JsonSerializable(typeof(DynamicDialogResult))]
	[JsonSerializable(typeof(DynamicDialogResult?))]
	[JsonSerializable(typeof(FileNameConflictResolveOptionType))]
	[JsonSerializable(typeof(FileNameConflictResolveOptionType?))]
	[JsonSerializable(typeof(FileOperationType))]
	[JsonSerializable(typeof(FileOperationType?))]
	[JsonSerializable(typeof(FileSystemStatusCode))]
	[JsonSerializable(typeof(FileSystemStatusCode?))]
	[JsonSerializable(typeof(FilesystemItemType))]
	[JsonSerializable(typeof(FilesystemItemType?))]
	[JsonSerializable(typeof(FilesystemOperationType))]
	[JsonSerializable(typeof(FilesystemOperationType?))]
	[JsonSerializable(typeof(FolderLayoutModes))]
	[JsonSerializable(typeof(FolderLayoutModes?))]
	[JsonSerializable(typeof(GitCheckoutOptions))]
	[JsonSerializable(typeof(GitCheckoutOptions?))]
	[JsonSerializable(typeof(GitOperationResult))]
	[JsonSerializable(typeof(GitOperationResult?))]
	[JsonSerializable(typeof(GridViewSizeKind))]
	[JsonSerializable(typeof(GridViewSizeKind?))]
	[JsonSerializable(typeof(GroupByDateUnit))]
	[JsonSerializable(typeof(GroupByDateUnit?))]
	[JsonSerializable(typeof(GroupOption))]
	[JsonSerializable(typeof(GroupOption?))]
	[JsonSerializable(typeof(IconOptions))]
	[JsonSerializable(typeof(IconOptions?))]
	[JsonSerializable(typeof(IconPersistenceOptions))]
	[JsonSerializable(typeof(IconPersistenceOptions?))]
	[JsonSerializable(typeof(ImpossibleActionResponseTypes))]
	[JsonSerializable(typeof(ImpossibleActionResponseTypes?))]
	[JsonSerializable(typeof(InfoPaneTabs))]
	[JsonSerializable(typeof(InfoPaneTabs?))]
	[JsonSerializable(typeof(ListViewSizeKind))]
	[JsonSerializable(typeof(ListViewSizeKind?))]
	[JsonSerializable(typeof(NetworkAvailability))]
	[JsonSerializable(typeof(NetworkAvailability?))]
	[JsonSerializable(typeof(OpenInIDEOption))]
	[JsonSerializable(typeof(OpenInIDEOption?))]
	[JsonSerializable(typeof(ParsedCommandType))]
	[JsonSerializable(typeof(ParsedCommandType?))]
	[JsonSerializable(typeof(PowerShellExecutionOptions))]
	[JsonSerializable(typeof(PowerShellExecutionOptions?))]
	[JsonSerializable(typeof(PreviewPaneStates))]
	[JsonSerializable(typeof(PreviewPaneStates?))]
	[JsonSerializable(typeof(PropertiesNavigationViewItemType))]
	[JsonSerializable(typeof(PropertiesNavigationViewItemType?))]
	[JsonSerializable(typeof(ReturnResult))]
	[JsonSerializable(typeof(ReturnResult?))]
	[JsonSerializable(typeof(SearchBoxTextChangeReason))]
	[JsonSerializable(typeof(SearchBoxTextChangeReason?))]
	[JsonSerializable(typeof(SettingsPageKind))]
	[JsonSerializable(typeof(SettingsPageKind?))]
	[JsonSerializable(typeof(ShellPaneArrangement))]
	[JsonSerializable(typeof(ShellPaneArrangement?))]
	[JsonSerializable(typeof(SingleClickOpenMode))]
	[JsonSerializable(typeof(SingleClickOpenMode?))]
	[JsonSerializable(typeof(SizeUnitTypes))]
	[JsonSerializable(typeof(SizeUnitTypes?))]
	[JsonSerializable(typeof(SortDirection))]
	[JsonSerializable(typeof(SortDirection?))]
	[JsonSerializable(typeof(SortOption))]
	[JsonSerializable(typeof(SortOption?))]
	[JsonSerializable(typeof(StatusCenterItemIconKind))]
	[JsonSerializable(typeof(StatusCenterItemIconKind?))]
	[JsonSerializable(typeof(StatusCenterItemKind))]
	[JsonSerializable(typeof(StatusCenterItemKind?))]
	[JsonSerializable(typeof(StatusCenterVisibility))]
	[JsonSerializable(typeof(StatusCenterVisibility?))]
	[JsonSerializable(typeof(WallpaperType))]
	[JsonSerializable(typeof(WallpaperType?))]
	[JsonSerializable(typeof(WindowsCompatDPIOptionKind))]
	[JsonSerializable(typeof(WindowsCompatDPIOptionKind?))]
	[JsonSerializable(typeof(WindowsCompatDpiOverrideKind))]
	[JsonSerializable(typeof(WindowsCompatDpiOverrideKind?))]
	[JsonSerializable(typeof(WindowsCompatModeKind))]
	[JsonSerializable(typeof(WindowsCompatModeKind?))]
	[JsonSerializable(typeof(WindowsCompatReducedColorModeKind))]
	[JsonSerializable(typeof(WindowsCompatReducedColorModeKind?))]
	[JsonSerializable(typeof(Files.App.UserControls.PreviewPanePositions))]
	[JsonSerializable(typeof(Files.App.UserControls.PreviewPanePositions?))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.HorizontalAlignment))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.HorizontalAlignment?))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.VerticalAlignment))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.VerticalAlignment?))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.Visibility))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.Visibility?))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.GridUnitType))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.GridUnitType?))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.GridLength))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.GridLength?))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.Media.Stretch))]
	[JsonSerializable(typeof(Microsoft.UI.Xaml.Media.Stretch?))]
	[JsonSerializable(typeof(JsonElement))]
	[JsonSerializable(typeof(JsonElement?))]
	[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
	[JsonSerializable(typeof(Dictionary<string, bool>))]
	[JsonSerializable(typeof(Dictionary<int, string>))]
	[JsonSerializable(typeof(bool?))]
	[JsonSerializable(typeof(byte?))]
	[JsonSerializable(typeof(int?))]
	[JsonSerializable(typeof(uint?))]
	[JsonSerializable(typeof(long?))]
	[JsonSerializable(typeof(ulong?))]
	[JsonSerializable(typeof(float?))]
	[JsonSerializable(typeof(double?))]
	[JsonSerializable(typeof(decimal?))]
	[JsonSerializable(typeof(DateTimeOffset?))]
	[JsonSerializable(typeof(TimeSpan?))]
	[JsonSerializable(typeof(Guid?))]
	internal sealed partial class AotJsonContext : JsonSerializerContext
	{
	}

	internal static class AotJson
	{
		public const string SerializerTrimJustification =
			"App JSON types are preserved via TrimmerRootAssembly and AotJsonContext supplies the value-type converter instantiations.";

		[System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2026", Justification = SerializerTrimJustification)]
		[System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("AOT", "IL3050", Justification = SerializerTrimJustification)]
		private static IJsonTypeInfoResolver CreateResolver()
			=> JsonTypeInfoResolver.Combine(AotJsonContext.Default, new DefaultJsonTypeInfoResolver());

		public static readonly IJsonTypeInfoResolver Resolver = CreateResolver();

		public static readonly JsonSerializerOptions Options = new()
		{
			TypeInfoResolver = Resolver
		};
	}
}
