trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
- group: BuildPipelineVariables
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'x64|ARM64'
- name: buildConfiguration
  value: 'Release'
- name: sideloadBuildConfiguration
  value: 'Sideload'
- name: appxPackageDir
  value: '$(build.artifactStagingDirectory)\AppxPackages\\'

jobs:
### Sideload release ###
- job: SideloadRelease
  timeoutInMinutes: 120
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        [xml]$xmlDoc = Get-Content '$(Build.SourcesDirectory)\src\Files.App (Package)\Package.appxmanifest'
        $xmlDoc.Package.Identity.Name="FilesPreview"
        $xmlDoc.Package.Identity.Publisher="Files"
        $xmlDoc.Package.Properties.DisplayName="Files - Preview"
        $xmlDoc.Package.Applications.Application.VisualElements.DisplayName="Files - Preview"
        $xmlDoc.Save('$(Build.SourcesDirectory)\src\Files.App (Package)\Package.appxmanifest')
      failOnStderr: true
      
 # This replaces references to the dev icon with the specified icon variant 
  - task: PowerShell@2
    displayName: 'Use Correct Logo'
    inputs:
      targetType: 'inline'
      script: |
        gci $(Build.SourcesDirectory)\src -Include *.csproj, *.appxmanifest, *.wapproj -recurse | ForEach -Process {
        (Get-Content $_ -Raw | ForEach -Process {$_ -replace "Assets\\AppTiles\\Dev", "Assets\AppTiles\Preview"}) | Set-Content $_ -NoNewline
        }
      failOnStderr: true

  - task: DownloadSecureFile@1
    name: mapsDevKey
    displayName: 'Download Bing Maps Dev Key'
    inputs:
      secureFile: 'BingMapsKey.txt'

# Adds the Bing maps token to the project
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: '$(mapsDevKey.secureFilePath)'
      TargetFolder: '$(Build.SourcesDirectory)\src\Files.App\Resources'
      overWrite: true

# Injects the AppCenter token to the project
  - task: PowerShell@2
    displayName: 'Inject AppCenter token'
    inputs:
      targetType: 'inline'
      script: |
        gci $(Build.SourcesDirectory)\src -Include *.cs -recurse | ForEach -Process {
        (Get-Content $_ -Raw | ForEach -Process {$_ -replace "appcenter.secret", "$(appcenter.secret)"}) | Set-Content $_ -NoNewline
        }
      failOnStderr: true

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 7.0.x
      includePreviewVersions: true

  - task: CmdLine@2
    inputs:
      script: |
        for /f %%a in ('dir /b /a:d %localappdata%\Microsoft\VisualStudio\17*') do echo UsePreviews=True>%localappdata%\Microsoft\VisualStudio\%%a\sdk.txt

  - task: MSBuild@1
    inputs:
      platform: 'x64'
      solution: '$(solution)'
      configuration: '$(sideloadBuildConfiguration)'
      msbuildArguments: '/t:restore /p:Configuration="$(sideloadBuildConfiguration)";Platform="$(buildPlatform)";PublishReadyToRun=true'
      maximumCpuCount: true

  - task: DownloadSecureFile@1
    name: caCertificate
    displayName: 'Download CA certificate'
    inputs:
      secureFile: '$(signingCert.secureFilePath)'

  - task: MSBuild@1
    inputs:
      solution: '**/*.wapproj'
      platform: 'x64'
      configuration: '$(sideloadBuildConfiguration)'
      msbuildArguments: '/t:build;_GenerateAppxPackage /p:AppxLogTelemetryFromSideloadingScript=False /p:GenerateAppInstallerFile=True /p:AppInstallerUri=https://cdn.files.community/files/preview/ /p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=Sideload /p:AppxPackageSigningEnabled=true /p:PackageCertificateKeyFile="$(caCertificate.secureFilePath)" /p:PackageCertificatePassword="$(signingCert.password)" /p:PackageCertificateThumbprint=""'
      maximumCpuCount: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\bin\$(sideloadBuildConfiguration)\**'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Sideload'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'Sideload'
      publishLocation: 'Container'

  - task: AzureFileCopy@4
    inputs:
      SourcePath: '$(build.artifactstagingdirectory)\AppxPackages\*'
      azureSubscription: 'azureconnection'
      Destination: 'AzureBlob'
      storage: 'filescommunity'
      ContainerName: 'files'
      BlobPrefix: 'preview'