trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 7.0.x
    includePreviewVersions: true

- task: PowerShell@2
  displayName: 'Check Xaml formatting'
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.SourcesDirectory)
      $changedFiles = (git diff --name-only) -split "\n" | Where-Object {$_ -like "*.xaml"}
      dotnet tool install --global XamlStyler.Console
      xstyler -p -f $changedFiles
    failOnStderr: true