name: Files Build Pipeline

on:
  push:
    branches-ignore:
    - 'dependabot**'
    tags-ignore:
    - '**'
  pull_request:
    paths-ignore:
    - '**.md'
    - '.github/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    env:
      SOLUTION_NAME: 'Files.sln'
      PACKAGE_PROJECT_NAME: '**/*.wapproj'
      CONFIGURATION: ${{ matrix.configuration }}
      PLATFORM: ${{ matrix.platform }}
      DEFAULT_DIR: ${{ github.workspace }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
  
    - name: Setup MSBuild
      id: setup_msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      id: setup-nuget
      uses: NuGet/setup-nuget@v1.1.1

    - name: Setup .NET SDK 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
  
    - name: Restore the projects
      id: restore_project
      shell: pwsh
      run: 'msbuild $env:SOLUTION_NAME /t:restore /p:Configuration="$env:CONFIGURATION" /p:Platform="$env:PLATFORM" /p:PublishReadyToRun=true'

    - name: Restore NuGet
      id: restore_nuget
      shell: pwsh
      run: 'nuget restore $env:SOLUTION_NAME'

    - name: Build and generate bundles
      id: build_app
      shell: pwsh
      run: |
        msbuild $env:PACKAGE_PROJECT_NAME
        /t:build;_GenerateAppxPackage
        /p:Platform=$env:PLATFORM
        /p:Configuration=$env:CONFIGURATION
        /p:UapAppxPackageBuildMode=$env:UAP_APPX_PACKAGE_BUILD_MODE
        /p:AppxBundle=$env:APPX_BUNDLE
        /p:AppxPackageSigningEnabled=$env:APPX_PACKAGE_SIGNING_ENABLED
        /p:AppxBundlePlatforms=$env:APPX_BUNDLE_PLATFORMS
        /p:AppxPackageDir=$env:ARTIFACTS_DIR
      env:
        UAP_APPX_PACKAGE_BUILD_MODE: CI
        APPX_BUNDLE: Never
        APPX_PACKAGE_SIGNING_ENABLED: false
        APPX_BUNDLE_PLATFORMS: ${{ matrix.platform }}
        ARTIFACTS_DIR: ${{ github.workspace }}\Artifacts
