name: Files Build Pipeline

on:
  push:
    branches-ignore:
    - 'dependabot**'
    tags-ignore:
    - '**'
  pull_request:
    paths-ignore:
    - '**.md'
    - '.builds/**'
    - '.specs/**'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug]
        platform: [x86, x64, arm64]
    env:
      SOLUTION_NAME: 'Files.sln'
      PACKAGE_PROJECT_NAME: 'src/Files.App (Package)/Files.Package.wapproj'
      PROJECT_RESTORE_PLATFORM: "x64"
      CONFIGURATION: ${{ matrix.configuration }}
      PLATFORM: ${{ matrix.platform }}
      DEFAULT_DIR: ${{ github.workspace }} # Default: D:\a\Files\Files\
      APPX_PACKAGE_DIR: ${{ github.workspace }}\AppxPackages
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
  
    - name: Setup MSBuild
      id: setup_msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      id: setup-nuget
      uses: NuGet/setup-nuget@v1.1.1
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.2

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
  
    - name: Restore Files
      id: restore_project
      shell: pwsh
      run: |
        msbuild $env:SOLUTION_NAME `
        -t:Restore `
        -p:Platform=$env:PROJECT_RESTORE_PLATFORM `
        -p:Configuration=$env:CONFIGURATION `
        -p:PublishReadyToRun=true `

    - name: Restore NuGet
      id: restore_nuget
      shell: pwsh
      run: 'nuget restore $env:SOLUTION_NAME'

    - name: Build Files
      id: build_app
      shell: pwsh
      run: |
        msbuild $env:PACKAGE_PROJECT_NAME `
        -t:Build `
        -p:Platform=$env:PLATFORM `
        -p:Configuration=$env:CONFIGURATION `
        -p:AppxBundle=Never `

    - name: Run Windows App Driver
      shell: pwsh
      run: '& "C:\Program Files\Windows Application Driver\winappdriver.exe"'

    - name: Build & run tests
      shell: pwsh
      run: |
        dotnet test tests\Files.InteractionTests\Files.InteractionTests.csproj
        -a $env:PLATFORM
        -c $env:CONFIGURATION
