# Builds and packages Files on GitHub's servers from your own fork.
# Copy this file to .github/workflows/build-my-fork.yml in your clone.

name: Build my fork

on:
  workflow_dispatch:
  push:
    branches:
      - bookmarks-bar

env:
  SOLUTION_PATH: '${{ github.workspace }}\Files.slnx'
  APP_PROJECT_PATH: '${{ github.workspace }}\src\Files.App\Files.App.csproj'
  ARTIFACTS_STAGING_DIR: '${{ github.workspace }}\artifacts'
  APPX_PACKAGE_DIR: '${{ github.workspace }}\artifacts\AppxPackages\'
  APPX_SELFSIGNED_CERT_PATH: '${{ github.workspace }}\.github\workflows\FilesApp_SelfSigned.pfx'
  CONFIGURATION: Release
  ARCHITECTURE: x64

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v6
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Restore Files
      shell: pwsh
      run: |
        msbuild $env:SOLUTION_PATH `
          -t:Restore `
          -p:Platform=$env:ARCHITECTURE `
          -p:Configuration=$env:CONFIGURATION `
          -p:PublishReadyToRun=true `
          -v:quiet

    - name: Create self signed cert as a pfx file
      run: ./.github/scripts/Generate-SelfCertPfx.ps1 -Destination "$env:APPX_SELFSIGNED_CERT_PATH"

    - name: Build & package Files
      run: |
        msbuild `
          $env:APP_PROJECT_PATH `
          -t:Build `
          -p:Configuration=$env:CONFIGURATION `
          -p:Platform=$env:ARCHITECTURE `
          -p:AppxBundlePlatforms=$env:ARCHITECTURE `
          -p:AppxBundle=Always `
          -p:GenerateAppxPackageOnBuild=true `
          -p:UapAppxPackageBuildMode=SideloadOnly `
          -p:AppxPackageDir=$env:APPX_PACKAGE_DIR `
          -p:AppxPackageSigningEnabled=true `
          -p:PackageCertificateKeyFile=$env:APPX_SELFSIGNED_CERT_PATH `
          -p:PackageCertificatePassword="" `
          -p:PackageCertificateThumbprint="" `
          -v:quiet

    - name: Upload the packages
      uses: actions/upload-artifact@v7
      with:
        name: 'Appx Packages (Release, x64)'
        path: ${{ env.ARTIFACTS_STAGING_DIR }}
