# Copyright (c) Files Community
# Licensed under the MIT License.

# Abstract:
#   This CI is executed when a new commit is created on the main branch or
#   on a PR whose head branch is the main branch.
#   However, the CI will not be executed if files not directly related to
#   source code maintenance are updated.

name: Files CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'assets/**'
      - 'builds/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'assets/**'
      - 'builds/**'
      - 'docs/**'
      - '*.md'

run-name: ${{ github.event_name == 'pull_request' && 'Files PR Validation' || 'Files CI Validation' }}

env:
  WORKING_DIR:                   '${{ github.workspace }}' # Default: 'D:\a\Files\Files'
  SOLUTION_PATH:                 '${{ github.workspace }}\Files.slnx'
  STARTUP_PROJECT_PATH:          '${{ github.workspace }}\src\Files.App\Files.App.csproj'
  AUTOMATED_TESTS_ARCHITECTURE:  'x64'
  AUTOMATED_TESTS_CONFIGURATION: 'Release'
  AUTOMATED_TESTS_PROJECT_DIR:   '${{ github.workspace }}\tests\Files.InteractionTests'
  AUTOMATED_TESTS_PROJECT_PATH:  '${{ github.workspace }}\tests\Files.InteractionTests\Files.InteractionTests.csproj'
  APPX_ARTIFACTS_PATH:           '${{ github.workspace }}\artifacts\' # The trailing backslash is needed
  APPX_SELFSIGNED_CERT_PATH:     '${{ github.workspace }}\FilesApp_SelfSigned.pfx'
  WINAPPDRIVER_EXE86_PATH:       'C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe'
  WINAPPDRIVER_EXE64_PATH:       'C:\Program Files\Windows Application Driver\WinAppDriver.exe'

jobs:

  check-formatting:

    if: github.repository_owner == 'files-community'

    runs-on: windows-latest

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Install XamlStyler.Console
      run: 'dotnet tool install --global XamlStyler.Console'

    - name: Check XAML formatting
      id: check-step
      run: |
        $changedFiles = (git diff --diff-filter=d --name-only HEAD~1) -split "\n" | Where-Object {$_ -like "*.xaml"}
        foreach ($file in $changedFiles)
        {
          xstyler -p -l None -f $file
          if ($LASTEXITCODE -ne 0)
          {
            echo "::error file=$file::Format check failed"
          }
        }
      continue-on-error: true
    
    - name: Fail if necessary
      if: steps.check-step.outcome == 'failure'
      run: exit 1

  build:

    if: github.repository_owner == 'files-community'

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      ARCHITECTURE: ${{ matrix.platform }}

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Build Files
      run: |
        ./.github/scripts/Build-AppSolution.ps1 `
            -ReleaseBranch               "$env:CONFIGURATION" `
            -SolutionPath                "$env:SOLUTION_PATH" `
            -StartupProjectPath          "$env:STARTUP_PROJECT_PATH" `
            -Configuration               "$env:CONFIGURATION" `
            -Platform                    "$env:ARCHITECTURE" `
            -AppxPackageDir              "$env:APPX_ARTIFACTS_PATH" `
            -AppxPackageCertKeyFilePath  "$env:APPX_SELFSIGNED_CERT_PATH"

    - if: env.ARCHITECTURE == env.AUTOMATED_TESTS_ARCHITECTURE && env.CONFIGURATION == env.AUTOMATED_TESTS_CONFIGURATION
      name: Upload the packages to the Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 'Appx Packages (${{ env.CONFIGURATION }}, ${{ env.ARCHITECTURE }})'
        path: '${{ env.APPX_ARTIFACTS_PATH }}'

  test:

    if: github.repository_owner == 'files-community' && always()

    needs: [build]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [x64]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      ARCHITECTURE: ${{ matrix.platform }}
    permissions:
      contents: read
      pull-requests: write

    steps:

    - if: contains(join(needs.*.result, ','), 'failure')
      name: Fail if necessary
      run: exit 1

    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Download the packages from the Artifacts
      uses: actions/download-artifact@v4
      with:
        name: 'Appx Packages (${{ env.CONFIGURATION }}, ${{ env.ARCHITECTURE }})'
        path: '${{ env.APPX_ARTIFACTS_PATH }}'

    - name: Prepare for the tests
      run: |
        msbuild -restore $env:AUTOMATED_TESTS_PROJECT_PATH /p:Configuration=$env:CONFIGURATION /p:Platform=$env:ARCHITECTURE
        Set-Location "$env:APPX_ARTIFACTS_PATH"
        $AppxPackageBundleDir = Get-ChildItem -Filter *_*_Test -Name
        Set-Location $AppxPackageBundleDir
        ./Install.ps1 -Force
        Set-DisplayResolution -Width 1920 -Height 1080 -Force
        Start-Process -FilePath "$env:WINAPPDRIVER_EXE86_PATH"

    # Retry integration tests if first attempt fails
    - name: Run the interaction tests
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 15
        max_attempts: 2
        shell: pwsh
        command: |
          dotnet test `
            --test-modules **\Files.InteractionTests.dll `
            --root-directory $env:AUTOMATED_TESTS_PROJECT_DIR\bin

    - if: github.event_name == 'pull_request'
      uses: geekyeggo/delete-artifact@v5
      with:
          name: '*'
